kind: pipeline
name: PBRP-RK134-TESTING

steps:
- name: cooked
  image: anggit86/dev:latest
  environment: 
    CHANNEL_ID:
      from_secret: CHANNEL_ID
    BOT_API_KEY:
      from_secret: BOT_API_KEY

  commands:
    - bash run.sh
